NAME=discord_bot

docker stop $NAME
docker rm $NAME

docker run \
-d \
-e DISCORD_TOKEN=$DISCORD_TOKEN \
-e SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID \
-e SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET \
-e SPOTIFY_REFRESH_TOKEN=$SPOTIFY_REFRESH_TOKEN \
-e SPOTIFY_PLAYLIST_ID=$SPOTIFY_PLAYLIST_ID \
--name $NAME \
--restart=on-failure \
"$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
